import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const sourceDir = path.join(root, "shared", "ruleset");
const targetFile = path.join(root, "frontend", "src", "ruleset.js");

if (!fs.existsSync(sourceDir)) {
  throw new Error(`[ruleset] missing shared ruleset at ${sourceDir}`);
}

const files = {
  scoring: "scoring.v1.json",
  economy: "economy.v1.json",
  mobs: "mobs.v1.json",
  caps: "caps.v1.json",
  towers: "towers.v1.json",
};

const data = {};
for (const [key, file] of Object.entries(files)) {
  const src = path.join(sourceDir, file);
  if (!fs.existsSync(src)) {
    throw new Error(`[ruleset] missing file ${src}`);
  }
  data[key] = JSON.parse(fs.readFileSync(src, "utf8"));
}

const payload = `// Auto-generated by scripts/sync-ruleset.js\n` +
  `export const RULESET_VERSION = \"v1\";\n` +
  `export const SCORING_RULES = ${JSON.stringify(data.scoring, null, 2)};\n` +
  `export const ECONOMY_RULES = ${JSON.stringify(data.economy, null, 2)};\n` +
  `export const MOB_RULES = ${JSON.stringify(data.mobs, null, 2)};\n` +
  `export const CAP_RULES = ${JSON.stringify(data.caps, null, 2)};\n` +
  `export const TOWER_RULES = ${JSON.stringify(data.towers, null, 2)};\n`;

fs.writeFileSync(targetFile, payload, "utf8");
console.log("[ruleset] synced", Object.values(files).join(", "));
