// Auto-generated by scripts/sync-ruleset.js
export const RULESET_VERSION = "v1";
export const SCORING_RULES = {
  "STRIDE": 1000000,
  "KILL_UNIT": 10,
  "HP_MAX": 9999
};
export const ECONOMY_RULES = {
  "goldStart": 60,
  "waveReward": [
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7,
    7
  ],
  "goldTolerance": 5
};
export const MOB_RULES = {
  "bossMultiplier": 2,
  "waveHpStep": 0.1,
  "mobs": {
    "bug": {
      "hp": 20,
      "dropGold": 1
    },
    "wolf": {
      "hp": 60,
      "dropGold": 4
    },
    "bat": {
      "hp": 50,
      "dropGold": 3
    },
    "fox": {
      "hp": 90,
      "dropGold": 4
    },
    "snake": {
      "hp": 80,
      "dropGold": 4
    },
    "turtle": {
      "hp": 120,
      "dropGold": 6
    },
    "boar": {
      "hp": 150,
      "dropGold": 6
    },
    "bear": {
      "hp": 160,
      "dropGold": 7
    },
    "scorpion": {
      "hp": 200,
      "dropGold": 8
    },
    "eagle": {
      "hp": 140,
      "dropGold": 8
    },
    "rhino": {
      "hp": 260,
      "dropGold": 11
    },
    "elephant": {
      "hp": 320,
      "dropGold": 13
    },
    "dragon": {
      "hp": 400,
      "dropGold": 18
    }
  }
};
export const CAP_RULES = {
  "maxMobsPerWave": [
    13,
    14,
    14,
    15,
    16,
    16,
    14,
    15,
    15,
    14,
    15,
    16,
    15,
    16,
    16,
    13,
    14,
    15,
    14,
    15,
    15,
    14,
    14,
    14,
    13,
    14,
    14,
    13,
    14,
    14
  ],
  "maxDamagePerWave": [
    560,
    715,
    828,
    1196,
    1470,
    1635,
    1856,
    2142,
    2250,
    3249,
    3800,
    4389,
    5082,
    5773,
    6048,
    6050,
    6760,
    7560,
    8568,
    9454,
    9960,
    11160,
    12096,
    12672,
    15096,
    17150,
    18144,
    17020,
    18544,
    19344
  ],
  "maxSpikeRatio": 3
};
